### ISSUE TITLE
Ambiguous error while compiling the examples

### ISSUE THREAD

**Issue by AdaBill** [EasyG0ing1/BlockNot#7] opened 2021-06-07 13:44 UTC
Looks like a great library, but when I tried to use an example (simple Blink) it gave me these errors. 

Arduino: 1.8.13 (Windows 10), Board: "Arduino Uno"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Willam\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Willam\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries -fqbn=arduino:avr:uno -ide-version=10813 -build-path C:\Users\Willam\AppData\Local\Temp\arduino_build_272847 -warnings=all -build-cache C:\Users\Willam\AppData\Local\Temp\arduino_cache_298532 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avrdude.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.arduinoOTA.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -verbose C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries\BlockNot\examples\BlockNotBlink\BlockNotBlink.ino

C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Willam\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Willam\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries -fqbn=arduino:avr:uno -ide-version=10813 -build-path C:\Users\Willam\AppData\Local\Temp\arduino_build_272847 -warnings=all -build-cache C:\Users\Willam\AppData\Local\Temp\arduino_cache_298532 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avrdude.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.arduinoOTA.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -verbose C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries\BlockNot\examples\BlockNotBlink\BlockNotBlink.ino

Using board 'uno' from platform in folder: C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.3

Using core 'arduino' from platform in folder: C:\Users\Willam\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.3

Detecting libraries used...

"C:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-IC:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\standard" "C:\\Users\\Willam\\AppData\\Local\\Temp\\arduino_build_272847\\sketch\\BlockNotBlink.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for BlockNot.h: [BlockNot@1.6.6]

ResolveLibrary(BlockNot.h)

  -> candidates: [BlockNot@1.6.6]

"C:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-IC:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\standard" "-IC:\\Users\\Willam\\Documents\\AAARDUINO_NEW\\External\\Arduino_Downloads\\Arduino-1.8.13-G-Sketches\\libraries\\BlockNot\\src" "C:\\Users\\Willam\\AppData\\Local\\Temp\\arduino_build_272847\\sketch\\BlockNotBlink.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Generating function prototypes...

"C:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-IC:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\standard" "-IC:\\Users\\Willam\\Documents\\AAARDUINO_NEW\\External\\Arduino_Downloads\\Arduino-1.8.13-G-Sketches\\libraries\\BlockNot\\src" "C:\\Users\\Willam\\AppData\\Local\\Temp\\arduino_build_272847\\sketch\\BlockNotBlink.ino.cpp" -o "C:\\Users\\Willam\\AppData\\Local\\Temp\\arduino_build_272847\\preproc\\ctags_target_for_gcc_minus_e.cpp" -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\builtin\\tools\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\Willam\\AppData\\Local\\Temp\\arduino_build_272847\\preproc\\ctags_target_for_gcc_minus_e.cpp"

Compiling sketch...

"C:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-IC:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\cores\\arduino" "-IC:\\Users\\Willam\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.3\\variants\\standard" "-IC:\\Users\\Willam\\Documents\\AAARDUINO_NEW\\External\\Arduino_Downloads\\Arduino-1.8.13-G-Sketches\\libraries\\BlockNot\\src" "C:\\Users\\Willam\\AppData\\Local\\Temp\\arduino_build_272847\\sketch\\BlockNotBlink.ino.cpp" -o "C:\\Users\\Willam\\AppData\\Local\\Temp\\arduino_build_272847\\sketch\\BlockNotBlink.ino.cpp.o"

BlockNotBlink:3:24: error: call of overloaded 'BlockNot(int)' is ambiguous

 BlockNot blinkTimer(100);

                        ^

In file included from C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries\BlockNot\examples\BlockNotBlink\BlockNotBlink.ino:1:0:

C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries\BlockNot\src/BlockNot.h:55:5: note: candidate: BlockNot::BlockNot(long unsigned int)

     BlockNot(unsigned long milliseconds) {

     ^~~~~~~~

C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries\BlockNot\src/BlockNot.h:50:5: note: candidate: BlockNot::BlockNot(bool)

     BlockNot(bool type) {

     ^~~~~~~~

C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries\BlockNot\src/BlockNot.h:36:7: note: candidate: constexpr BlockNot::BlockNot(const BlockNot&)

 class BlockNot {

       ^~~~~~~~

C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries\BlockNot\src/BlockNot.h:36:7: note: candidate: constexpr BlockNot::BlockNot(BlockNot&&)

C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries\BlockNot\examples\BlockNotBlink\BlockNotBlink.ino: In function 'void loop()':

BlockNotBlink:21:5: error: expected ';' before '}' token

     }

     ^

Using library BlockNot at version 1.6.6 in folder: C:\Users\Willam\Documents\AAARDUINO_NEW\External\Arduino_Downloads\Arduino-1.8.13-G-Sketches\libraries\BlockNot 

exit status 1

call of overloaded 'BlockNot(int)' is ambiguous

**Comment by AdaBill** [comment] 2021-06-07 14:34
I was able to get around the problem by adding (unsigned long) to the value. 

BlockNot blinkTimer((unsigned long)100);

The sketch then compiled and executed properly.

I think it is something you have to do in the library, but for my needs, this solved the immediate problem

**Comment by AdaBill** [comment] 2021-06-07 18:02
It is expecting an unsigned long for EVERY time entry.  so just add, regardless of the actual magnitude of the number.

BlockNot blinkTimer(100UL);
BlockNot blinkTimer(10UL);
BlockNot blinkTimer(320000UL);

**Comment by bizprof** [comment] 2021-06-10 12:31
@AdaBill, yes, totally agree, adding "UL" to the time values would fix this issue. OTH, the examples should compile as-is, at least for the supported board(s), without any code changes required. The ambiguity might have been caused by the code for the SECONDS feature, which introduced another single-parameter call to the BlockNot constructor. That confused the compiler. Should be fixed in a future release, hopefully. Was just about to create a PR for another issue, might add some code to disambiguate the constructor call as well...

**Comment by AdaBill** [comment] 2021-06-10 13:21
The BlockNot is a great function. I have used it several times on my sketches now and it does make life a lot easier not having to play the millis() game.  Thanks for all your hard work and it must be rewarding to see your library used and appreciated.

Bill

Sent from Mail for Windows 10

**Comment by EasyG0ing1** [comment] 2021-06-11 04:43
@AdaBill 

This issue has been fixed in release 1.6.7.

Thank you for creating the issue and sorry it took so long.

**Closed as completed by EasyG0ing1** 2021-06-11 04:43 UTC
